@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for alfresco-identity-service:1.1.0

'There are 3 referenced Helm Charts
artifact "postgresql:0.15.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: databus23\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql" as postgresql_0_15_0 #LightSteelBlue
artifact "alfresco-identity-service:1.1.0\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/stable\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: \n\t\talfresco\n\t\tkeycloak\n\t\tidentity-service" as alfresco_identity_service_1_1_0 #Chartreuse
artifact "keycloak:4.3.0\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tkeycloak\n\t\taccess-management" as keycloak_4_3_0 #LightBlue

'There are 2 referenced Docker Images
usecase "Image\n====\nDocker Hub\n====\npostgres\n====\n10.1" as postgres_10_1 #Ivory
usecase "Image\n====\nDocker Hub\n====\njboss/keycloak\n====\n4.8.3.Final" as jboss_keycloak_4_8_3_Final #LemonChiffon

'Chart Dependencies
alfresco_identity_service_1_1_0--[#green]-|>keycloak_4_3_0
keycloak_4_3_0--[#green]-|>postgresql_0_15_0
postgresql_0_15_0--[#orange]-|>postgres_10_1
keycloak_4_3_0--[#orange]-|>jboss_keycloak_4_8_3_Final

center footer Generated on 2022/05/05 00:15:29 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
