@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for alfresco-identity-service:4.0.0

'There are 4 referenced Helm Charts
artifact "common:1.4.1\n====\n\tType: library\n====\n\tRepo: N/A - Explicit Dependency\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_4_1 #DarkSeaGreen
artifact "alfresco-identity-service:4.0.0\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/stable\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: \n\t\talfresco\n\t\tkeycloak\n\t\tidentity-service" as alfresco_identity_service_4_0_0 #Chartreuse
artifact "postgresql:10.3.13\n====\n\tType: application\n====\n\tRepo: N/A - Explicit Dependency\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_10_3_13 #LightSteelBlue
artifact "keycloak:11.0.1\n====\n\tType: application\n====\n\tRepo: https://codecentric.github.io/helm-charts\n====\n\tMaintainers: \n\t\tunguiculus\n\t\tthomasdarimont\n====\n\tKeywords: \n\t\tsso\n\t\tidm\n\t\topenid connect\n\t\tsaml\n\t\tkerberos\n\t\tldap" as keycloak_11_0_1 #LightBlue

'There are 2 referenced Docker Images
usecase "Image\n====\nquay.io\n====\nalfresco/alfresco-identity-service:1.5.0\n====\n1.5.0" as quay_io_alfresco_alfresco_identity_service_1_5_0 #Azure
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:11.11.0-debian-10-r31\n====\n11.11.0-debian-10-r31" as docker_io_bitnami_postgresql_11_11_0_debian_10_r31 #DarkSalmon

'Chart Dependencies
alfresco_identity_service_4_0_0--[#green]-|>keycloak_11_0_1
keycloak_11_0_1--[#green]-|>postgresql_10_3_13
postgresql_10_3_13--[#green]-|>common_1_4_1
postgresql_10_3_13--[#orange]-|>docker_io_bitnami_postgresql_11_11_0_debian_10_r31
keycloak_11_0_1--[#orange]-|>quay_io_alfresco_alfresco_identity_service_1_5_0

center footer Generated on 2022/06/09 16:49:30 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
