@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for nuxeo:3.0.9

'There is one referenced Helm Chart
artifact "nuxeo:3.0.9\n====\n\tType: application\n====\n\tRepo: https://chartmuseum.platform.dev.nuxeo.com/\n====\n\tMaintainers: \n====\n\tKeywords: " as nuxeo_3_0_9 #LightSeaGreen

'There is one referenced Docker Image
usecase "Image\n====\ndocker-private.packages.nuxeo.com\n====\nnuxeo/nuxeo:2021\n====\n2021" as docker_private_packages_nuxeo_com_nuxeo_nuxeo_2021 #LightSkyBlue

'Chart Dependencies
nuxeo_3_0_9--[#orange]-|>docker_private_packages_nuxeo_com_nuxeo_nuxeo_2021

center footer Generated on 2022/06/09 16:45:15 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
