@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for alfresco-content-services:5.2.0

'There are 8 referenced Helm Charts
artifact "common:7.2.0\n====\n\tType: application\n====\n\tRepo: Unknown Repo URL\n====\n\tMaintainers: \n====\n\tKeywords: " as common_7_2_0 #DarkSeaGreen
artifact "alfresco-insight-zeppelin:1.0.3\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tzeppelin\n\t\tinsight zeppelin\n\t\talfresco zeppelin\n\t\talfresco insight zeppelin" as alfresco_insight_zeppelin_1_0_3 #GhostWhite
artifact "alfresco-search:1.0.4\n====\n\tType: application\n====\n\tRepo: Unknown Repo URL\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tsearch\n\t\tsearch services\n\t\talfresco search services\n\t\tinsight\n\t\tinsight engine\n\t\talfresco insight engine" as alfresco_search_1_0_4 #GhostWhite
artifact "postgresql:10.16.2\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_10_16_2 #LightSteelBlue
artifact "alfresco-content-services:5.2.0\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tcontent\n\t\tcontent services\n\t\talfresco\n\t\talfresco content services" as alfresco_content_services_5_2_0 #Gainsboro
artifact "activemq:2.1.0\n====\n\tType: application\n====\n\tRepo: Unknown Repo URL\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tactivemq\n\t\tmessage broker" as activemq_2_1_0 #LightBlue
artifact "alfresco-sync-service:3.0.9\n====\n\tType: application\n====\n\tRepo: Unknown Repo URL\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tsyncservice\n\t\talfresco\n\t\tapplication" as alfresco_sync_service_3_0_9 #CadetBlue
artifact "common:1.10.3\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_10_3 #DarkSeaGreen

'There are 14 referenced Docker Images
usecase "Image\n====\nquay.io\n====\nalfresco/alfresco-share:7.2.0\n====\n7.2.0" as quay_io_alfresco_alfresco_share_7_2_0 #LemonChiffon
usecase "Image\n====\nDocker Hub\n====\nalfresco/alfresco-pdf-renderer\n====\n2.5.7" as alfresco_alfresco_pdf_renderer_2_5_7 #Cornsilk
usecase "Image\n====\nquay.io\n====\nalfresco/alfresco-transform-router:1.5.2\n====\n1.5.2" as quay_io_alfresco_alfresco_transform_router_1_5_2 #Aqua
usecase "Image\n====\nDocker Hub\n====\nalfresco/alfresco-tika\n====\n2.5.7" as alfresco_alfresco_tika_2_5_7 #DeepSkyBlue
usecase "Image\n====\nDocker Hub\n====\nalfresco/alfresco-activemq\n====\n5.16.4-jre11-centos7" as alfresco_alfresco_activemq_5_16_4_jre11_centos7 #Khaki
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:13.3.0\n====\n13.3.0" as docker_io_bitnami_postgresql_13_3_0 #DarkSalmon
usecase "Image\n====\nquay.io\n====\nalfresco/alfresco-content-repository:7.2.0\n====\n7.2.0" as quay_io_alfresco_alfresco_content_repository_7_2_0 #GoldenRod
usecase "Image\n====\nDocker Hub\n====\nalfresco/alfresco-imagemagick\n====\n2.5.7" as alfresco_alfresco_imagemagick_2_5_7 #Aqua
usecase "Image\n====\nDocker Hub\n====\nalfresco/alfresco-libreoffice\n====\n2.5.7" as alfresco_alfresco_libreoffice_2_5_7 #LightSkyBlue
usecase "Image\n====\nquay.io\n====\nalfresco/alfresco-shared-file-store:0.16.1\n====\n0.16.1" as quay_io_alfresco_alfresco_shared_file_store_0_16_1 #Lavender
usecase "Image\n====\nquay.io\n====\nalfresco/insight-zeppelin:1.4.0\n====\n1.4.0" as quay_io_alfresco_insight_zeppelin_1_4_0 #GreenYellow
usecase "Image\n====\nDocker Hub\n====\nalfresco/alfresco-transform-misc\n====\n2.5.7" as alfresco_alfresco_transform_misc_2_5_7 #LightSkyBlue
usecase "Image\n====\nquay.io\n====\nalfresco/service-sync:3.6.0\n====\n3.6.0" as quay_io_alfresco_service_sync_3_6_0 #LightPink
usecase "Image\n====\nquay.io\n====\nalfresco/search-services:2.0.3\n====\n2.0.3" as quay_io_alfresco_search_services_2_0_3 #Aquamarine

'Chart Dependencies
alfresco_content_services_5_2_0--[#green]-|>alfresco_sync_service_3_0_9
alfresco_content_services_5_2_0--[#green]-|>activemq_2_1_0
alfresco_content_services_5_2_0--[#green]-|>postgresql_10_16_2
postgresql_10_16_2--[#green]-|>common_1_10_3
alfresco_content_services_5_2_0--[#green]-|>common_7_2_0
alfresco_content_services_5_2_0--[#green]-|>alfresco_search_1_0_4
alfresco_search_1_0_4--[#green]-|>alfresco_insight_zeppelin_1_0_3
alfresco_insight_zeppelin_1_0_3--[#orange]-|>quay_io_alfresco_insight_zeppelin_1_4_0
alfresco_search_1_0_4--[#orange]-|>quay_io_alfresco_search_services_2_0_3
postgresql_10_16_2--[#orange]-|>docker_io_bitnami_postgresql_13_3_0
alfresco_content_services_5_2_0--[#orange]-|>quay_io_alfresco_alfresco_share_7_2_0
alfresco_content_services_5_2_0--[#orange]-|>quay_io_alfresco_alfresco_content_repository_7_2_0
alfresco_content_services_5_2_0--[#orange]-|>alfresco_alfresco_imagemagick_2_5_7
alfresco_content_services_5_2_0--[#orange]-|>alfresco_alfresco_tika_2_5_7
alfresco_content_services_5_2_0--[#orange]-|>alfresco_alfresco_pdf_renderer_2_5_7
alfresco_content_services_5_2_0--[#orange]-|>alfresco_alfresco_libreoffice_2_5_7
alfresco_content_services_5_2_0--[#orange]-|>quay_io_alfresco_alfresco_shared_file_store_0_16_1
alfresco_content_services_5_2_0--[#orange]-|>alfresco_alfresco_transform_misc_2_5_7
alfresco_content_services_5_2_0--[#orange]-|>quay_io_alfresco_alfresco_transform_router_1_5_2
activemq_2_1_0--[#orange]-|>alfresco_alfresco_activemq_5_16_4_jre11_centos7
alfresco_sync_service_3_0_9--[#orange]-|>quay_io_alfresco_service_sync_3_6_0

center footer Generated on 2022/05/05 00:12:38 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
