@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for wordpress:13.1.4

'There are 4 referenced Helm Charts
artifact "wordpress:13.1.4\n====\n\twordpress\n====\n\t13.1.4\n====\napplication\n====\n\thttps://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: application\nblog\ncms\nhttp\nphp\nweb\nwordpress" as wordpress_13_1_4 #GreenYellow
artifact "mariadb:10.4.2\n====\n\tmariadb\n====\n\t10.4.2\n====\napplication\n====\n\thttps://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: mariadb\nmysql\ndatabase\nsql\nprometheus" as mariadb_10_4_2 #DarkTurquoise
artifact "memcached:6.0.7\n====\n\tmemcached\n====\n\t6.0.7\n====\napplication\n====\n\thttps://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: memcached\ncache" as memcached_6_0_7 #DarkSeaGreen
artifact "common:1.12.0\n====\n\tcommon\n====\n\t1.12.0\n====\nlibrary\n====\n\thttps://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: common\nhelper\ntemplate\nfunction\nbitnami" as common_1_12_0 #DarkSeaGreen

'There are 3 referenced Docker Images
usecase "Image\n====\n\tdocker.io\n====\n\tbitnami/mariadb:10.5.15-debian-10-r30\n====\n\t10.5.15-debian-10-r30" as docker_io_bitnami_mariadb_10_5_15_debian_10_r30 #DarkGoldenRod
usecase "Image\n====\n\tdocker.io\n====\n\tbitnami/memcached:1.6.14-debian-10-r34\n====\n\t1.6.14-debian-10-r34" as docker_io_bitnami_memcached_1_6_14_debian_10_r34 #CadetBlue
usecase "Image\n====\n\tdocker.io\n====\n\tbitnami/wordpress:5.9.2-debian-10-r9\n====\n\t5.9.2-debian-10-r9" as docker_io_bitnami_wordpress_5_9_2_debian_10_r9 #Darkorange

'Chart Dependencies
wordpress_13_1_4--[#green]-|>common_1_12_0
wordpress_13_1_4--[#green]-|>mariadb_10_4_2
mariadb_10_4_2--[#green]-|>common_1_12_0
wordpress_13_1_4--[#green]-|>memcached_6_0_7
memcached_6_0_7--[#green]-|>common_1_12_0
wordpress_13_1_4--[#orange]-|>docker_io_bitnami_wordpress_5_9_2_debian_10_r9
mariadb_10_4_2--[#orange]-|>docker_io_bitnami_mariadb_10_5_15_debian_10_r30
memcached_6_0_7--[#orange]-|>docker_io_bitnami_memcached_1_6_14_debian_10_r34

center footer Generated on 2022/03/24 12:08:23 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
