@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for wordpress:14.2.5

'There are 5 referenced Helm Charts
artifact "memcached:6.0.20\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmemcached\n\t\tcache" as memcached_6_0_20 #DarkSeaGreen
artifact "common:1.14.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_0 #DarkSeaGreen
artifact "wordpress:14.2.5\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tapplication\n\t\tblog\n\t\tcms\n\t\thttp\n\t\tphp\n\t\tweb\n\t\twordpress" as wordpress_14_2_5 #GreenYellow
artifact "common:1.14.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_1 #DarkSeaGreen
artifact "mariadb:11.0.6\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tprometheus" as mariadb_11_0_6 #DarkTurquoise

'There are 3 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/mariadb:10.6.7-debian-10-r91\n====\n10.6.7-debian-10-r91" as docker_io_bitnami_mariadb_10_6_7_debian_10_r91 #DarkGoldenRod
usecase "Image\n====\ndocker.io\n====\nbitnami/wordpress:5.9.3-debian-10-r48\n====\n5.9.3-debian-10-r48" as docker_io_bitnami_wordpress_5_9_3_debian_10_r48 #Darkorange
usecase "Image\n====\ndocker.io\n====\nbitnami/memcached:1.6.15-debian-10-r49\n====\n1.6.15-debian-10-r49" as docker_io_bitnami_memcached_1_6_15_debian_10_r49 #CadetBlue

'Chart Dependencies
wordpress_14_2_5--[#green]-|>memcached_6_0_20
memcached_6_0_20--[#green]-|>common_1_14_0
wordpress_14_2_5--[#green]-|>mariadb_11_0_6
mariadb_11_0_6--[#green]-|>common_1_14_0
wordpress_14_2_5--[#green]-|>common_1_14_1
memcached_6_0_20--[#orange]-|>docker_io_bitnami_memcached_1_6_15_debian_10_r49
wordpress_14_2_5--[#orange]-|>docker_io_bitnami_wordpress_5_9_3_debian_10_r48
mariadb_11_0_6--[#orange]-|>docker_io_bitnami_mariadb_10_6_7_debian_10_r91

center footer Generated on 2022/06/09 15:05:29 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
